### ISSUE TITLE
帮助

### ISSUE THREAD

**Issue by hustStt** [JimChengLin/open_hikv#1]
您好，请问有后续实现完成的版本吗？

**Comment by JimChengLin** [comment]
在做了

**Comment by JimChengLin** [comment]
> 您好，请问有后续实现完成的版本吗？

实现了一版，我发现根本没办法写一个合理的基于 Intel TSX 的 B+Tree，高 cotention 下 abort 的概率也太高了。你有啥经验吗？

**Comment by LikoJ** [comment]
您好，请问您目前实现的版本可以分享一下嘛？我想使用YCSB对HIKV做一个简单的测试。如果可以的话非常感谢。

**Comment by JimChengLin** [comment]
> 您好，请问您目前实现的版本可以分享一下嘛？我想使用YCSB对HIKV做一个简单的测试。如果可以的话非常感谢。

老实说我也想啊，但是 HiKV 关键的 Intel TSX B+ Tree 压根没搞定，我可以把目前的实现放上来。目前我的打算就测试单线程的了。

**Comment by LikoJ** [comment]
> > 您好，请问您目前实现的版本可以分享一下嘛？我想使用YCSB对HIKV做一个简单的测试。如果可以的话非常感谢。
> 
> 老实说我也想啊，但是 HiKV 关键的 Intel TSX B+ Tree 压根没搞定，我可以把目前的实现放上来。目前我的打算就测试单线程的了。

单线程是指现在向HIKV存KV需要依次对B+树和Hash表进行写入嘛，还是说只能支持单线程的YCSB输入？我还是想测试一下，如果可以的话请您上传一下吧，非常感谢！

**Comment by JimChengLin** [comment]
@LikoJ 我上传了，具体实现的框架有了，除了原论文的 TSX B+Tree 别的应该算是有点样子了。

有两点注意：
1. 无锁 Hash 要求预先定义大小
2. 很多地方有泄漏，但我都写了注释

综合来看，我觉得复现 HiKV 没啥价值，细节没交代清楚。我去换别的 KVStore 去实现了。

**Comment by JimChengLin** [comment]
@LikoJ TSX B+Tree 我拿了个开源代码风格还不错的实现加了 TSX 指令，烂爆了。甚至我发现我把 printf 注释掉后，就卡死。推测是因为高并发下 TSX abort 率太高。

我咨询过 Intel 官方人士，这个破指令集压根大厂没人用。我谨代表我个人怀疑任何基于 TSX 的论文都在放卫星。

**Comment by JimChengLin** [comment]
我的 vx：jimzuolin 欢迎交流，最近要做个 PMEM 上 Index 的对比，可能可以合作。

**Comment by LikoJ** [comment]
> @LikoJ 我上传了，具体实现的框架有了，除了原论文的 TSX B+Tree 别的应该算是有点样子了。
> 
> 有两点注意：
> 
> 1. 无锁 Hash 要求预先定义大小
> 2. 很多地方有泄漏，但我都写了注释
> 
> 综合来看，我觉得复现 HiKV 没啥价值，细节没交代清楚。我去换别的 KVStore 去实现了。



> @LikoJ TSX B+Tree 我拿了个开源代码风格还不错的实现加了 TSX 指令，烂爆了。甚至我发现我把 printf 注释掉后，就卡死。推测是因为高并发下 TSX abort 率太高。
> 
> 我咨询过 Intel 官方人士，这个破指令集压根大厂没人用。我谨代表我个人怀疑任何基于 TSX 的论文都在放卫星。

非常感谢您愿意分享代码，我也没有使用过TSX的经验，网上搜了一下仿佛确实没什么人用，也许已经被intel放弃了吧。后续如果有运行方面的问题还请您指点一下。

**Comment by Gumi-presentation-by-Dzh** [comment]
> 我的 vx：jimzuolin 欢迎交流，最近要做个 PMEM 上 Index 的对比，可能可以合作。

希望能够将在PMEM上index橫测的项目也能开源，这对后续研究工作者follow会有很大的帮助。若只考虑论文结果和实现可能存在很大的水分。而且在PMEM的index工作往往都是割裂了，无法从整体衡量性能的优劣。

另外，现有的Hikv若不考虑复现准确性（和paper一不一样已经无所谓了），是否能运行一些常用的KV benchmark？

**Comment by JimChengLin** [comment]
> > 我的 vx：jimzuolin 欢迎交流，最近要做个 PMEM 上 Index 的对比，可能可以合作。
> 
> 希望能够将在PMEM上index橫测的项目也能开源，这对后续研究工作者follow会有很大的帮助。若只考虑论文结果和实现可能存在很大的水分。而且在PMEM的index工作往往都是割裂了，无法从整体衡量性能的优劣。
> 
> 另外，现有的Hikv若不考虑复现准确性（和paper一不一样已经无所谓了），是否能运行一些常用的KV benchmark？

如果我复现了应该会开源，如果是已经开源了的，我会把编译步骤写出来。

HiKV 的 Hash 和 Queue 我应该已经实现好了（跟论文差不多）。B+Tree 要自己补充或者用 plain_vanilla 的实现，不考虑析构啥的，应该凑合能跑跑。
